In [45]:
import numpy as np
import pandas as pd

In [46]:
df=pd.read_csv("jobs.csv")
df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [47]:
df.shape

(123849, 31)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

In [49]:
df.columns.tolist()

['job_id',
 'company_name',
 'title',
 'description',
 'max_salary',
 'pay_period',
 'location',
 'company_id',
 'views',
 'med_salary',
 'min_salary',
 'formatted_work_type',
 'applies',
 'original_listed_time',
 'remote_allowed',
 'job_posting_url',
 'application_url',
 'application_type',
 'expiry',
 'closed_time',
 'formatted_experience_level',
 'skills_desc',
 'listed_time',
 'posting_domain',
 'sponsored',
 'work_type',
 'currency',
 'compensation_type',
 'normalized_salary',
 'zip_code',
 'fips']

In [50]:
keep=["title",
      "company_name",
      "location",
      "max_salary","med_salary","min_salary",
      "formatted_work_type","applies","views","remote_allowed"]

df=df[keep]

In [51]:
df.head()

,title,company_name,location,max_salary,med_salary,min_salary,formatted_work_type,applies,views,remote_allowed
0,Marketing Coordinator,Corcoran Sawyer Smith,"Princeton, NJ",20.0,NaN,17.0,Full-time,2.0,20.0,NaN
1,Mental Health Therapist/Counselor,NaN,"Fort Collins, CO",50.0,NaN,30.0,Full-time,NaN,1.0,NaN
2,Assitant Restaurant Manager,The National Exemplar,"Cincinnati, OH",65000.0,NaN,45000.0,Full-time,NaN,8.0,NaN
3,Senior Elder Law / Trusts and Estates Associat...,"Abrams Fensterman, LLP","New Hyde Park, NY",175000.0,NaN,140000.0,Full-time,NaN,16.0,NaN
4,Service Technician,NaN,"Burlington, IA",80000.0,NaN,60000.0,Full-time,NaN,3.0,NaN

In [52]:
df.isnull().sum()

title                       0
company_name             1719
location                    0
max_salary              94056
med_salary             117569
min_salary              94056
formatted_work_type         0
applies                100529
views                    1689
remote_allowed         108603
dtype: int64

In [53]:
df=df.dropna(subset=["title","location"])

In [54]:
df.isnull().sum()

title                       0
company_name             1719
location                    0
max_salary              94056
med_salary             117569
min_salary              94056
formatted_work_type         0
applies                100529
views                    1689
remote_allowed         108603
dtype: int64

In [55]:
df["company_name"]=(df["company_name"].fillna("Unknown"))

In [56]:
df.isnull().sum()

title                       0
company_name                0
location                    0
max_salary              94056
med_salary             117569
min_salary              94056
formatted_work_type         0
applies                100529
views                    1689
remote_allowed         108603
dtype: int64

In [57]:
salary_df=df.dropna(subset=["med_salary"])

In [58]:
salary_df["med_salary"].describe()

count      6280.000000
mean      22015.619876
std       52255.873846
min           0.000000
25%          18.940000
50%          25.500000
75%        2510.500000
max      750000.000000
Name: med_salary, dtype: float64

In [78]:
df["views"]=(df["views"].fillna(df["views"].median()).astype(int))

In [69]:
df["applies"]=(df["applies"].fillna(0))

In [73]:
df["applies"]=(df["applies"].astype(int))

In [81]:
df["remote_allowed"]=(df["remote_allowed"].fillna("Unknown"))

In [84]:
salary_df=(df.dropna(subset=["med_salary"]))

In [85]:
salary_df.shape

(6280, 10)

In [87]:
df.isnull().sum()

title                       0
company_name                0
location                    0
max_salary              94056
med_salary             117569
min_salary              94056
formatted_work_type         0
applies                     0
views                       0
remote_allowed              0
dtype: int64

In [89]:
df.to_csv("clean_jobs.csv",index=False)